### ISSUE TITLE
simulator run-android 

### ISSUE THREAD

**Issue by spencercap** [decosoftware/deco-components#20]
hi, wonderful work with deco but the android simulator doesnt seem to work. when running `react-native run-android` i get a BUILD FAILED error: `Task 'installDebug' not found in root project 'Project'.` so it appears that there's a issue with this usual step `Building and installing the app on the device (cd android && ./gradlew installDebug...` 

are you trying to load a different kind of debug menu? 

from what I've gathered, to build and deploy the android app you now need "app" and "keystores" folders in the /android folder and within those are tons of project specific paths. ALSO, in /node_modules/react-native it seems there now needs to be a "react.gradle" file you can get by starting a new normal 'react-native init Project'. 
But I did try it out and changed all this, was able to install the app on an android emulator now getting the error: `TransformError: /Users/Spencer/Desktop/react-native/tests/intro/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js: Path must be a string. Received undefined` 

overall seems like initializing a new project in Deco needs a little boost with respect to android.

**Comment by spencercap** [comment]
nevermind, solved this. 

used standard `react-native init Project` then opened it in Deco, works just fine.

**Comment by gdowens** [comment]
Yes, at the moment default Project android doesn't work. Should be fixed in next release.
